// Kernel unit tests. Every expected value here is hand-derived (worked out
// independently on paper / from the public format docs), never generated by
// running the code under test and freezing its output.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseXER, num } from '../src/kernel/xer-parser.js';
import {
  parseP6Date, serialToUTC, parseClndrData, makeCalendar, hoursOnDay,
  isWorkingDay, workingDaysBetween, addWorkingDays, spreadAcrossPeriods,
} from '../src/kernel/calendar.js';
import { buildModel } from '../src/kernel/model.js';
import { runCPM, criticalPathTest } from '../src/kernel/cpm.js';
import { computeEarnedPct, computeEVM } from '../src/kernel/evm.js';
import { rollupWBS } from '../src/kernel/wbs.js';
import { runAllChecks } from '../src/kernel/dcma.js';
import { extractChainage, findOutOfSequence } from '../src/kernel/chainage.js';
import { resourceDemand } from '../src/kernel/resource.js';
import { compareModels } from '../src/kernel/compare.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');
const U = (y, m, d, hh = 0, mm = 0) => Date.UTC(y, m - 1, d, hh, mm);

const current = buildModel(parseXER(read('tests/fixtures/najd-s2-update.xer')));
const baseline = buildModel(parseXER(read('tests/fixtures/najd-s2-baseline.xer')));
const byCode = (c) => current.taskByCode.get(c);

// ---------- parser ----------

test('parser: header, tables, short rows, split-table append', () => {
  const text = [
    'ERMHDR\t19.12\t2026-01-01\tProject',
    '%T\tFOO',
    '%F\ta\tb\tc',
    '%R\t1\t2\t3',
    '%R\t4\t5', // short row: trailing field undefined, not ""
    '%T\tBAR',
    '%F\tx',
    '%R\t9',
    '%T\tFOO', // same logical table, second block: APPEND, never overwrite
    '%F\ta\tb\tc',
    '%R\t7\t8\t9',
    '%E',
  ].join('\n');
  const { tables, header } = parseXER(text);
  assert.equal(header.version, '19.12');
  assert.equal(tables.FOO.length, 3);
  assert.equal(tables.FOO[1].c, undefined);
  assert.equal(tables.FOO[2].a, '7');
  assert.equal(tables.BAR.length, 1);
});

test('parser: numeric coercion — zero is a value, absent is not', () => {
  assert.equal(num('0'), 0);
  assert.equal(num(''), undefined);
  assert.equal(num(undefined), undefined);
  assert.equal(num('abc'), undefined);
  assert.equal(num('-40'), -40);
});

// ---------- calendar ----------

test('dates: P6 strings parse as UTC, never local-shifted', () => {
  assert.equal(parseP6Date('2026-07-01 07:00'), U(2026, 7, 1, 7, 0));
  assert.equal(parseP6Date('2025-09-07'), U(2025, 9, 7));
  assert.equal(parseP6Date(''), undefined);
});

test('calendar: Lotus serial epoch 1899-12-30 (hand-derived anchors)', () => {
  // Excel/Lotus serial for 2025-01-01 is 45658 (public anchor);
  // 2025-09-23 is 265 days later => 45923.
  assert.equal(serialToUTC(45658), U(2025, 1, 1));
  assert.equal(serialToUTC(45923), U(2025, 9, 23));
});

test('calendar: clndr_data grammar — spec example decodes correctly', () => {
  const s = '(0||CalendarData()((0||DaysOfWeek()((0||1()((0||0(s|08:00|f|16:00)())))(0||2()((0||0(s|08:00|f|16:00)())))(0||6()())(0||7()())))(0||VIEW(ShowTotal|N)())(0||Exceptions()((0||0(d|45731)())(0||3(d|45736)((0||0(s|08:00|f|12:00)())))))))';
  const { week, exceptions } = parseClndrData(s);
  assert.equal(week[1].length, 1);              // Sunday working
  assert.equal(week[6].length, 0);              // Friday non-working
  assert.equal(exceptions.size, 2);
  assert.deepEqual(exceptions.get(serialToUTC(45731)), []);          // full holiday
  assert.equal(exceptions.get(serialToUTC(45736)).length, 1);        // partial day
});

test('calendar: fixture Sun–Thu calendar + KSA exceptions', () => {
  const cal = current.calendars.get('100');
  assert.ok(cal);
  assert.equal(isWorkingDay(cal, U(2026, 6, 7)), true);   // Sunday
  assert.equal(isWorkingDay(cal, U(2026, 6, 5)), false);  // Friday
  assert.equal(isWorkingDay(cal, U(2025, 9, 23)), false); // National Day exception
  assert.equal(hoursOnDay(cal, U(2026, 3, 18)), 4);       // Eid half-day 07:00–11:00
  assert.equal(hoursOnDay(cal, U(2026, 6, 7)), 8);
});

test('working-day math: hand-counted Sun–Thu week', () => {
  const cal = current.calendars.get('100');
  // 2026-01-04 is a Sunday; [Jan 4, Jan 11) contains Sun–Thu = 5 working days
  assert.equal(workingDaysBetween(cal, U(2026, 1, 4), U(2026, 1, 11)), 5);
  // Thursday + 1 working day = next Sunday
  assert.equal(addWorkingDays(cal, U(2026, 1, 8), 1), U(2026, 1, 11));
});

test('spreadAcrossPeriods: month boundary split, hand-derived 50/50', () => {
  const cal = current.calendars.get('100');
  // Tue 2026-01-27 .. Tue 2026-02-03: working days Jan 27,28,29 + Feb 1,2,3
  const m = spreadAcrossPeriods(cal, U(2026, 1, 27), U(2026, 2, 3), 100, 'month');
  assert.ok(Math.abs(m.get('2026-01') - 50) < 1e-9);
  assert.ok(Math.abs(m.get('2026-02') - 50) < 1e-9);
});

// ---------- model ----------

test('model: all 43 activities survive the split TASK table', () => {
  assert.equal(current.tasks.length, 43);
  assert.ok(byCode('M-110')); // lives in the second %T TASK block
});

test('model: data date prefers last_schedule_date over last_recalc_date', () => {
  assert.equal(current.dataDateSource, 'last_schedule_date');
  assert.equal(current.dataDate, U(2026, 7, 1, 7, 0));
  // baseline has no last_schedule_date -> falls back, documented
  assert.equal(baseline.dataDateSource, 'last_recalc_date');
});

test('model: absent numeric fields stay undefined, never 0', () => {
  const done = byCode('S31-030');
  assert.equal(done.status, 'TK_Complete');
  assert.equal(done.totalFloatHrs, undefined); // float blank for completed
  const neg = byCode('T-010');
  assert.equal(neg.totalFloatHrs, -40);        // negative is a real value
});

test('model: phys_complete_pct is 0–100, milestones detected', () => {
  assert.equal(byCode('S33-050').physPct, 55);
  assert.equal(byCode('A-000').milestone, true);
  assert.equal(byCode('S31-030').milestone, false);
});

// ---------- chainage ----------

test('chainage: KP extraction, null for no match', () => {
  assert.equal(extractChainage('Trench Excavation KP512+000 to KP518+000'), 512);
  assert.equal(extractChainage('Wadi Hanifa HDD Crossing KP529+800'), 529.8);
  assert.equal(extractChainage('Pre-commissioning & Dewatering'), null);
});

test('chainage: exactly the one engineered out-of-sequence pair', () => {
  const oos = findOutOfSequence(current);
  assert.equal(oos.length, 1);
  assert.equal(oos[0].pred.code, 'S33-050'); // welding KP524–530
  assert.equal(oos[0].succ.code, 'T-020');   // tie-in back at KP518+400
});

// ---------- CPM (hand-derived 4-node network) ----------

test('CPM: forward/backward pass matches hand calculation', () => {
  // A(5) -FS-> B(10) -FS-> D(2);  A -SS+2d-> C(3) -FS-> D
  // Hand: A 0-5, B 5-15, C es 2 ef 5, D es 15 ef 17; TF: A0 B0 C10 D0
  const cal = { dayHrs: 8 };
  const mk = (id, d) => ({ id, code: id, milestone: false, origDays: d });
  const fake = {
    tasks: [mk('A', 5), mk('B', 10), mk('C', 3), mk('D', 2)],
    preds: [
      { taskId: 'B', predTaskId: 'A', type: 'PR_FS', lagHrs: 0 },
      { taskId: 'C', predTaskId: 'A', type: 'PR_SS', lagHrs: 16 },
      { taskId: 'D', predTaskId: 'B', type: 'PR_FS', lagHrs: 0 },
      { taskId: 'D', predTaskId: 'C', type: 'PR_FS', lagHrs: 0 },
    ],
    projectCal: cal,
    taskById: new Map(),
  };
  fake.taskById = new Map(fake.tasks.map((t) => [t.id, t]));
  const r = runCPM(fake);
  assert.equal(r.cyclic, false);
  assert.equal(r.finishDays, 17);
  const n = (id) => r.nodes.get(id);
  assert.equal(n('A').es, 0); assert.equal(n('A').tf, 0);
  assert.equal(n('B').es, 5); assert.equal(n('B').tf, 0);
  assert.equal(n('C').es, 2); assert.equal(n('C').tf, 10);
  assert.equal(n('D').es, 15); assert.equal(n('D').tf, 0);
});

test('CPM: cycle detection reports instead of hanging', () => {
  const mk = (id, d) => ({ id, code: id, milestone: false, origDays: d });
  const fake = {
    tasks: [mk('A', 5), mk('B', 5)],
    preds: [
      { taskId: 'B', predTaskId: 'A', type: 'PR_FS', lagHrs: 0 },
      { taskId: 'A', predTaskId: 'B', type: 'PR_FS', lagHrs: 0 },
    ],
    projectCal: { dayHrs: 8 },
    taskById: new Map(),
  };
  assert.equal(runCPM(fake).cyclic, true);
});

test('CPM: critical path test passes on the demo network (real perturbation)', () => {
  const r = criticalPathTest(current);
  assert.equal(r.status, 'pass');
  assert.equal(r.shift, r.extendBy);
});

// ---------- EVM ----------

test('EVM: earned % rules — the fabrication guards', () => {
  const asOf = U(2026, 7, 1);
  // phys 55 => 0.55 (0–100 convention, always /100)
  assert.equal(computeEarnedPct(byCode('S33-050'), asOf), 0.55);
  // phys 1 => 0.01 — NOT re-interpreted as "already fractional"
  assert.equal(computeEarnedPct({ status: 'TK_Active', physPct: 1 }, asOf), 0.01);
  // unstarted activity with an elapsed window earns 0, never "planned progress"
  assert.equal(computeEarnedPct({
    status: 'TK_NotStart', physPct: undefined, actStart: undefined,
    targetStart: U(2026, 1, 1), targetEnd: U(2026, 2, 1),
  }, asOf), 0);
  // complete => 1
  assert.equal(computeEarnedPct(byCode('S31-030'), asOf), 1);
});

test('EVM: PV is a curve, EV/AC are single points at the data date', () => {
  const evm = computeEVM(current);
  assert.ok(evm.pv.length > 10);                       // full time-phased plan
  assert.equal(evm.evPoint.date, current.dataDate);    // exactly one point
  assert.equal(evm.acPoint.date, current.dataDate);
  const last = evm.pv[evm.pv.length - 1];
  assert.ok(Math.abs(last.cum - evm.bac) < 1e-6);      // curve sums to BAC
  // behind schedule + over cost, as engineered
  assert.ok(evm.spi.value > 0.5 && evm.spi.value < 1);
  assert.ok(evm.cpi.value > 0.7 && evm.cpi.value < 1);
  assert.ok(evm.eac > evm.bac);                        // overrun forecast
});

test('EVM: N/A is distinct from a real zero', () => {
  const evm = computeEVM(baseline); // baseline data date precedes plan start
  assert.equal(evm.spi.value, null);
  assert.ok(evm.spi.reason.length > 0);
});

// ---------- WBS rollup ----------

test('WBS rollup: cost-weighted, at the data date', () => {
  const { stats } = rollupWBS(current);
  const segA = stats.get('5031'); // fully complete segment
  assert.ok(Math.abs(segA.pct - 1) < 1e-9);
  const segD = stats.get('5034'); // barely started segment
  assert.ok(segD.pct < 0.15);
  const root = stats.get('5000');
  assert.equal(root.taskCount, 43);
  assert.ok(root.pct > 0.5 && root.pct < 0.85); // not "everything ~100%"
});

// ---------- DCMA ----------

test('DCMA: engineered offender counts', () => {
  const checks = runAllChecks(current, { baseline });
  const c = (id) => checks.find((x) => x.id === id);
  assert.equal(checks.length, 14);

  assert.equal(c(1).count, 2);            // C-020 no successor, C-030 no predecessor
  assert.equal(c(2).count, 1);            // the HDD lead
  assert.equal(c(2).status, 'pass');
  assert.equal(c(3).count, 6);            // 4×SS+40h, 1×FF+80h, 1×FS+80h
  assert.equal(c(4).status, 'pass');      // exactly 90% FS
  assert.equal(c(5).count, 2);            // CS_MEO + CS_MANDFIN
  assert.equal(c(5).status, 'pass');
  assert.equal(c(6).count, 1);            // P-040, 60 wd float — 1/19 just over 5%
  assert.equal(c(6).status, 'fail');
  assert.equal(c(7).count, 10);           // the negative-float chain
  assert.equal(c(7).status, 'fail');
  assert.equal(c(8).count, 1);            // S34 welding at 46 wd
  assert.equal(c(9).count, 6);            // stale forecasts: S33-060/070, S34-030/040/050, P-040
  assert.equal(c(10).status, 'info');
  assert.equal(c(10).count, 0);           // every real activity is resourced
  assert.equal(c(11).status, 'fail');     // most of the job slipped vs baseline
  assert.equal(c(12).status, 'pass');     // real CPM perturbation
  assert.equal(c(13).status, 'fail');     // CPLI < 0.95 with -5d driving float
  assert.ok(c(13).value > 0.7 && c(13).value < 0.95);
  assert.equal(c(14).status, 'fail');     // BEI well under 0.95
  assert.ok(c(14).value < 0.95);
});

test('DCMA: baseline-dependent checks are N/A without one — never defaulted', () => {
  const checks = runAllChecks(current, {});
  for (const id of [11, 13, 14]) {
    const c = checks.find((x) => x.id === id);
    assert.equal(c.status, 'na');
    assert.equal(c.value, null);
    assert.ok(c.reason && c.reason.length > 0);
  }
});

// ---------- resources ----------

test('resources: over-allocation only where a ceiling exists', () => {
  const d = resourceDemand(current, 'week');
  assert.ok(d.overalloc.length > 0);
  for (const o of d.overalloc) assert.equal(o.rsrc.id, '203'); // only the sideboom
  const noCeilIds = d.noCeiling.map((r) => r.id).sort();
  assert.deepEqual(noCeilIds, ['204', '205', '207']); // reported, not defaulted
});

// ---------- compare ----------

test('compare: matched by code; added/removed explicit; critical shift as set diff', () => {
  const cmp = compareModels(current, baseline);
  assert.equal(cmp.added.length, 1);
  assert.equal(cmp.added[0].code, 'C-030');
  assert.equal(cmp.removed.length, 1);
  assert.equal(cmp.removed[0].code, 'S31-025');
  assert.equal(cmp.matched.length, 42);
  // Segment A never moved: slip 0
  const s31 = cmp.matched.find((m) => m.code === 'S31-030');
  assert.equal(s31.slipDays, 0);
  // Segment B moved 5 wd later wholesale
  const s32 = cmp.matched.find((m) => m.code === 'S32-010');
  assert.equal(s32.slipDays, 5);
  // critical set shift: S33-050/060 + six S34 tasks became critical; none left
  const now = cmp.nowCritical.map((t) => t.code).sort();
  assert.deepEqual(now, ['S33-050', 'S33-060', 'S34-020', 'S34-030', 'S34-040', 'S34-050', 'S34-060', 'S34-070']);
  assert.equal(cmp.leftCritical.length, 0);
});
