// Period Report — the look-back: for the chosen window, what was done, what
// started, what was planned and missed, milestones hit and missed, and the
// value of work completed (real actual dates) against planned value. With a
// copy-ready plain-text report for the weekly email and CSV export.
import { fmtDate } from '../kernel/calendar.js';
import { openModal } from '../ui/modal.js';
import {
  esc, fmtMoney, statTile, taskModalBody, naTag,
  windowBarHTML, wireWindowBar, downloadCSV, isoDate,
} from '../ui/components.js';

function repTable(el, store, items, cols, mapRow, emptyText) {
  if (!items.length) return `<p class="sub" style="margin:4px 0 0">${esc(emptyText)}</p>`;
  return `<div class="tablewrap"><table class="ledger">
    <thead><tr>${cols.map((c) => `<th class="${c.num ? 'num' : ''}">${esc(c.h)}</th>`).join('')}</tr></thead>
    <tbody>${items.map((it, i) => `<tr class="rowlink" data-rep="${el}:${i}" tabindex="0">${mapRow(it)}</tr>`).join('')}</tbody>
  </table></div>`;
}

function slipCell(slipWd) {
  if (slipWd === undefined) return `<td class="num">${naTag('no data date')}</td>`;
  return `<td class="num" style="color:var(--bad)">+${slipWd} wd</td>`;
}

function buildReportText(store, rep) {
  const m = store.model;
  const L = [];
  const line = (s = '') => L.push(s);
  line(`PROGRESS REPORT — ${store.modelName}`);
  line(`Window: ${fmtDate(rep.from)} to ${fmtDate(rep.to)} · Data date: ${fmtDate(m.dataDate)}`);
  line('='.repeat(64));
  line();
  line(`COMPLETED IN WINDOW (${rep.completed.length}) — value ${fmtMoney(rep.valueDone)}`);
  for (const t of rep.completed) line(`  ${t.code.padEnd(10)} ${t.name}  [${fmtDate(t.actEnd)}]`);
  line();
  line(`STARTED IN WINDOW (${rep.started.length})`);
  for (const t of rep.started) line(`  ${t.code.padEnd(10)} ${t.name}  [${fmtDate(t.actStart)}]`);
  line();
  line(`MISSED FINISHES (${rep.missedFinish.length}) — planned to finish, not complete`);
  for (const { t, slipWd } of rep.missedFinish) line(`  ${t.code.padEnd(10)} ${t.name}  planned ${fmtDate(t.targetEnd)}${slipWd !== undefined ? ` · ${slipWd} wd behind` : ''}`);
  line();
  line(`MISSED STARTS (${rep.missedStart.length}) — planned to start, not started`);
  for (const { t, slipWd } of rep.missedStart) line(`  ${t.code.padEnd(10)} ${t.name}  planned ${fmtDate(t.targetStart)}${slipWd !== undefined ? ` · ${slipWd} wd behind` : ''}`);
  line();
  line(`MILESTONES — hit ${rep.milestonesHit.length}, missed ${rep.milestonesMissed.length}`);
  for (const t of rep.milestonesHit) line(`  ✓ ${t.code.padEnd(10)} ${t.name}  [${fmtDate(t.actEnd ?? t.actStart)}]`);
  for (const t of rep.milestonesMissed) line(`  ✗ ${t.code.padEnd(10)} ${t.name}  planned ${fmtDate(t.targetEnd)}`);
  line();
  line(`Planned value in window: ${fmtMoney(rep.valuePlanned)} · Completed value: ${fmtMoney(rep.valueDone)}`);
  line(`Generated by PRISM Deep Field — values derived only from the XER's own fields.`);
  return L.join('\n');
}

export const ViewReport = {
  id: 'report', title: 'Period Report', group: 'Reporting',
  chip(store) {
    return `<span class="num">${isoDate(store.win.from)} → ${isoDate(store.win.to)}</span>`;
  },
  render(el, store) {
    const m = store.model;
    const rep = store.d.report;
    const doneTone = rep.completed.length >= rep.missedFinish.length ? 'good' : 'warn';

    el.innerHTML = `
      <div class="section">
        <h2>Period report</h2>
        <p class="sub">The look-back for the chosen window: completions and starts come from recorded actual dates; "missed" means planned inside the window's elapsed portion and still not done — future work is never called late.</p>
        ${windowBarHTML(store)}
        <div class="statrow" style="margin-top:14px">
          ${statTile({ id: 'done', label: 'Completed', value: `<span class="num">${rep.completed.length}</span>`, tone: doneTone, note: fmtMoney(rep.valueDone) + ' value' })}
          ${statTile({ id: 'started', label: 'Started', value: `<span class="num">${rep.started.length}</span>`, note: 'actual starts in window' })}
          ${statTile({ id: 'missf', label: 'Missed finishes', value: `<span class="num">${rep.missedFinish.length}</span>`, tone: rep.missedFinish.length ? 'bad' : 'good', note: 'planned, not complete' })}
          ${statTile({ id: 'misss', label: 'Missed starts', value: `<span class="num">${rep.missedStart.length}</span>`, tone: rep.missedStart.length ? 'warn' : 'good', note: 'planned, not started' })}
          ${statTile({ id: 'pv', label: 'Planned value', value: `<span class="num" style="font-size:19px">${esc(fmtMoney(rep.valuePlanned))}</span>`, note: 'calendar-spread in window' })}
        </div>
        <div class="filterrow" style="margin-top:12px">
          <span class="spacer"></span>
          <button class="btn small" data-csv>Export CSV</button>
          <button class="btn small primary" data-report-text>Copy report text</button>
        </div>
      </div>

      <div class="section">
        <h2>Completed in window <span class="num" style="color:var(--good)">${rep.completed.length}</span></h2>
        ${repTable('done', store, rep.completed,
          [{ h: 'Code' }, { h: 'Activity' }, { h: 'Actual finish', num: true }, { h: 'Value', num: true }],
          (t) => `<td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.actEnd)}</td><td class="num">${esc(fmtMoney(t.targetCost))}</td>`,
          'Nothing completed in this window.')}
      </div>

      <div class="section">
        <h2>Missed finishes <span class="num" style="color:${rep.missedFinish.length ? 'var(--bad)' : 'var(--good)'}">${rep.missedFinish.length}</span></h2>
        <p class="sub">Planned to finish in the window's elapsed portion, still not complete — ranked by working days behind.</p>
        ${repTable('missf', store, rep.missedFinish,
          [{ h: 'Code' }, { h: 'Activity' }, { h: 'Planned finish', num: true }, { h: 'Behind', num: true }, { h: 'Status' }],
          ({ t, slipWd }) => `<td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.targetEnd)}</td>${slipCell(slipWd)}<td>${t.status === 'TK_Active' ? 'in progress' : 'not started'}</td>`,
          'No missed finishes in this window.')}
      </div>

      <div class="section">
        <h2>Missed starts <span class="num" style="color:${rep.missedStart.length ? 'var(--warn)' : 'var(--good)'}">${rep.missedStart.length}</span></h2>
        ${repTable('misss', store, rep.missedStart,
          [{ h: 'Code' }, { h: 'Activity' }, { h: 'Planned start', num: true }, { h: 'Behind', num: true }],
          ({ t, slipWd }) => `<td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.targetStart)}</td>${slipCell(slipWd)}`,
          'No missed starts in this window.')}
      </div>

      <div class="section">
        <h2>Started in window <span class="num">${rep.started.length}</span></h2>
        ${repTable('started', store, rep.started,
          [{ h: 'Code' }, { h: 'Activity' }, { h: 'Actual start', num: true }, { h: 'Status' }],
          (t) => `<td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.actStart)}</td><td>${t.status === 'TK_Complete' ? 'complete' : 'in progress'}</td>`,
          'Nothing started in this window.')}
      </div>

      <div class="section">
        <h2>Milestones</h2>
        ${rep.milestonesHit.length || rep.milestonesMissed.length ? `
          <div class="tablewrap"><table class="ledger"><tbody>
            ${rep.milestonesHit.map((t, i) => `<tr class="rowlink" data-rep="mh:${i}" tabindex="0"><td><span class="pill pass">hit</span></td><td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.actEnd ?? t.actStart)}</td></tr>`).join('')}
            ${rep.milestonesMissed.map((t, i) => `<tr class="rowlink" data-rep="mm:${i}" tabindex="0"><td><span class="pill fail">missed</span></td><td class="num">${esc(t.code)}</td><td>${esc(t.name)}</td><td class="num">${fmtDate(t.targetEnd)}</td></tr>`).join('')}
          </tbody></table></div>`
        : '<p class="sub">No milestones fall in this window.</p>'}
      </div>`;

    wireWindowBar(el, store);

    const lists = {
      done: rep.completed, started: rep.started,
      missf: rep.missedFinish.map((x) => x.t), misss: rep.missedStart.map((x) => x.t),
      mh: rep.milestonesHit, mm: rep.milestonesMissed,
    };
    el.querySelectorAll('[data-rep]').forEach((tr) => {
      const open = () => {
        const [k, i] = tr.dataset.rep.split(':');
        const t = lists[k][+i];
        if (t) openModal(`${t.code} — ${t.name}`, 'period report detail', taskModalBody(t, m));
      };
      tr.addEventListener('click', open);
      tr.addEventListener('keydown', (e) => { if (e.key === 'Enter') open(); });
    });

    el.querySelector('[data-csv]').addEventListener('click', () => {
      const rows = [];
      for (const t of rep.completed) rows.push(['completed', t.code, t.name, isoDate(t.actEnd), t.targetCost || '']);
      for (const t of rep.started) rows.push(['started', t.code, t.name, isoDate(t.actStart), '']);
      for (const { t, slipWd } of rep.missedFinish) rows.push(['missed_finish', t.code, t.name, isoDate(t.targetEnd), slipWd ?? '']);
      for (const { t, slipWd } of rep.missedStart) rows.push(['missed_start', t.code, t.name, isoDate(t.targetStart), slipWd ?? '']);
      for (const t of rep.milestonesHit) rows.push(['milestone_hit', t.code, t.name, isoDate(t.actEnd ?? t.actStart), '']);
      for (const t of rep.milestonesMissed) rows.push(['milestone_missed', t.code, t.name, isoDate(t.targetEnd), '']);
      downloadCSV(`period_report_${isoDate(rep.from)}_${isoDate(rep.to)}.csv`,
        ['category', 'code', 'name', 'date', 'value_or_slip_wd'], rows);
    });

    el.querySelector('[data-report-text]').addEventListener('click', () => {
      const text = buildReportText(store, rep);
      const card = openModal('Report text', 'paste into the weekly email / client report', `
        <textarea data-report-body spellcheck="false" style="width:100%;height:300px;background:rgba(5,6,11,.6);color:var(--text);border:1px solid var(--border);border-radius:8px;padding:10px;font:12px/1.5 var(--mono);resize:vertical"></textarea>`,
        `<button class="btn small primary" data-copy>Copy to clipboard</button>`);
      card.querySelector('[data-report-body]').value = text;
      card.querySelector('[data-copy]').addEventListener('click', async (e) => {
        try { await navigator.clipboard.writeText(text); e.target.textContent = 'Copied ✓'; }
        catch { card.querySelector('[data-report-body]').select(); document.execCommand('copy'); e.target.textContent = 'Copied ✓'; }
      });
    });
  },
};
